-- Plantillas actualizadas entregadas por el consultorio el 8 de octubre de 2026.
-- Fuente: 62 PDF AcroForm; 61 tratamientos y un recetario vacío excluido.
-- Guarda la versión previa de las semillas y de las filas que actualiza.
-- Conserva activas las plantillas personalizadas. No modifica recetas emitidas.

begin;

lock table public.plantillas_receta in share row exclusive mode;
alter table public.plantillas_receta add column if not exists versiones_anteriores jsonb not null default '[]'::jsonb;
alter table public.plantillas_receta add column if not exists origen_actualizacion text;

update public.plantillas_receta p
set versiones_anteriores = p.versiones_anteriores || jsonb_build_array(to_jsonb(p) - 'versiones_anteriores'),
    origen_actualizacion = 'archivo-20261008'
where p.origen_actualizacion is null and (p.categoria, p.nombre) in (
('FASE 1', 'COMBINADO 2 PASTILLAS FASE 1'),
('FASE 1', 'COMBINADO 21 DIAS'),
('FASE 1', 'COMBINADO FASE 1-FEDRA'),
('FASE 1', 'KWIKPEN 2.5 COMBINADO FASE 1'),
('FASE 1', 'KWIKPEN 2.5 mg'),
('FASE 1', 'NOTA'),
('FASE 1', 'PASTILLA FASE 1'),
('FASE 1', 'PASTILLA FASE 1 15 DIAS'),
('FASE 1', 'PASTILLA FASE 1 de 21 días'),
('FASE 1', 'RYBELSUS 3mg COMBINADO FASE 1'),
('FASE 1', 'RYBELSUS FASE 1 30 DÍAS'),
('FASE 1', 'SAXENDA FASE 1-FEDRA'),
('FASE 1', 'WEGOVY COMBINADO FASE 1'),
('FASE 1', 'WEGOVY FASE 1'),
('FASE 2', 'COMBINADO 30 DIAS FASE 3'),
('FASE 2', 'COMBINADO FASE 3 15 DIAS'),
('FASE 2', 'COMBINADO RYBELSUS 30 DIAS'),
('FASE 2', 'KWIKPEN COMBINADO FASE 3'),
('FASE 2', 'MOUNJARO COMBINADO FASE 3'),
('FASE 2', 'PASTILLAS 15 DIAS FASE 3'),
('FASE 2', 'PASTILLAS 30 DIAS FASE 3'),
('FASE 2', 'SAXENDA 3'),
('FASE 2', 'WEGOVY COMBINADO FASE 3'),
('FASE 2', 'WEGOVY FASE 3'),
('FASE 3 y 4', 'COMBINADO 15 DIAS.'),
('FASE 3 y 4', 'COMBINADO FASE 5'),
('FASE 3 y 4', 'COMBINADO RYBELSUS'),
('FASE 3 y 4', 'KWIKPEN COMBINADO FASE 5'),
('FASE 3 y 4', 'KWIKPEN FASE 5'),
('FASE 3 y 4', 'MOUNJARO COMBINADO FASE 5'),
('FASE 3 y 4', 'PASTILLAS 15 DIAS FASE 5'),
('FASE 3 y 4', 'PASTILLAS 30 DIAS FASE 5'),
('FASE 3 y 4', 'WEGOVY COMBINADO FASE 5'),
('FASE 3 y 4', 'WEGOVY FASE 5'),
('FASE 5', 'combinado 15 días-FEDRA'),
('FASE 5', 'COMBINADO 21 DÍAS-FEDRA'),
('FASE 5', 'combinado 30 días 2 pastillas-FEDRA'),
('FASE 5', 'Combinado Retomar 30 días 1 pastilla-FEDRA'),
('FASE 5', 'MOUNJARO COMBINADO RETOMAR'),
('FASE 5', 'pastilla 21 días'),
('FASE 5', 'Pastillas 30 días 2 termogenicos'),
('FASE 5', 'Retomar 30 días 1 pastilla'),
('FASE 5', 'RETOMAR RYBELSUS Pastillas 30 días'),
('FASE 5', 'Victoza 23 días'),
('FASE 5', 'WEGOVY COMBINADO RETOMAR 21 DIAS'),
('FASE 5', 'WEGOVY COMBINADO RETOMAR 30 DIAS'),
('FASE 5', 'Wikpen COMBINADO RETOMAR 30 DIAS'),
('Mantenimiento', 'Mantenimiento 1 pastilla'),
('RETOMAR', 'DESTETE COMBINADO'),
('RETOMAR', 'DESTETE COMBINADO KWIKPEN'),
('RETOMAR', 'DESTETE COMBINADO WEGOBY'),
('RETOMAR', 'DESTETE MOUNJARO'),
('RETOMAR', 'DESTETE PASTILLA'),
('RETOMAR', 'DESTETE SAXENDA'),
('FASE 1', 'COMBINADO 2 PASTILLAS FASE 1'),
('FASE 1', 'COMBINADO 21 DIAS'),
('FASE 1', 'COMBINADO FASE 1-FEDRA'),
('FASE 1', 'KWIKPEN 2.5 COMBINADO FASE 1'),
('FASE 1', 'KWIKPEN 2.5 mg'),
('FASE 1', 'NOTA'),
('FASE 1', 'PASTILLA FASE 1 15 DIAS'),
('FASE 1', 'PASTILLA FASE 1 de 21 días'),
('FASE 1', 'PASTILLA FASE 1'),
('FASE 1', 'RYBELSUS 3mg COMBINADO FASE 1'),
('FASE 1', 'RYBELSUS FASE 1 30 DÍAS'),
('FASE 1', 'SAXENDA FASE 1-FEDRA'),
('FASE 1', 'WEGOVY COMBINADO FASE 1'),
('FASE 1', 'WEGOVY FASE 1'),
('FASE 2', 'COMBINADO FASE 2 15 DÍAS'),
('FASE 2', 'COMBINADO FASE 2 21 DIAS'),
('FASE 2', 'COMBINADO FASE 2 de 30 días pdf'),
('FASE 2', 'KWIKPEN COMBINADO FASE 2'),
('FASE 2', 'KWIKPEN FASE 2'),
('FASE 2', 'PASTILLA FASE 2 21 DIAS'),
('FASE 2', 'PASTILLA fase 2 de 15 días'),
('FASE 2', 'RYBELSUS 3'),
('FASE 2', 'RYBELSUS COMBINADO 3 mg'),
('FASE 2', 'SAXENDA'),
('FASE 2', 'WEGOVY COMBINADO FASE 2 21 DIAS'),
('FASE 2', 'WEGOVY FASE 2'),
('FASE 3 y 4', 'COMBINADO 30 DIAS FASE 3'),
('FASE 3 y 4', 'COMBINADO FASE 3 15 DIAS'),
('FASE 3 y 4', 'COMBINADO RYBELSUS 30 DIAS'),
('FASE 3 y 4', 'KWIKPEN COMBINADO FASE 3'),
('FASE 3 y 4', 'MOUNJARO COMBINADO FASE 3'),
('FASE 3 y 4', 'PASTILLAS 15 DIAS FASE 3'),
('FASE 3 y 4', 'PASTILLAS 30 DIAS FASE 3'),
('FASE 3 y 4', 'SAXENDA 3'),
('FASE 3 y 4', 'WEGOVY COMBINADO FASE 3'),
('FASE 3 y 4', 'WEGOVY FASE 3'),
('FASE 5', 'COMBINADO 15 DIAS.'),
('FASE 5', 'COMBINADO FASE 5'),
('FASE 5', 'COMBINADO RYBELSUS'),
('FASE 5', 'KWIKPEN COMBINADO FASE 5'),
('FASE 5', 'KWIKPEN FASE 5'),
('FASE 5', 'MOUNJARO COMBINADO FASE 5'),
('FASE 5', 'PASTILLAS 15 DIAS FASE 5'),
('FASE 5', 'PASTILLAS 30 DIAS FASE 5'),
('FASE 5', 'WEGOVY FASE 5'),
('FASE 5', 'WEGOVY COMBINADO FASE 5'),
('Mantenimiento', 'Mantenimiento 1 pastilla'),
('RETOMAR', 'COMBINADO 21 DÍAS-FEDRA'),
('RETOMAR', 'Combinado Retomar 30 días 1 pastilla-FEDRA'),
('RETOMAR', 'MOUNJARO COMBINADO RETOMAR'),
('RETOMAR', 'Pastillas 30 días 2 termogenicos'),
('RETOMAR', 'RETOMAR RYBELSUS Pastillas 30 días'),
('RETOMAR', 'Retomar 30 días 1 pastilla'),
('RETOMAR', 'Saxenda 23 días'),
('RETOMAR', 'Victoza 23 días'),
('RETOMAR', 'WEGOVY COMBINADO RETOMAR 21 DIAS'),
('RETOMAR', 'WEGOVY COMBINADO RETOMAR 30 DIAS'),
('RETOMAR', 'Wikpen COMBINADO RETOMAR 30 DIAS'),
('RETOMAR', 'combinado 15 días-FEDRA'),
('RETOMAR', 'combinado 30 días 2 pastillas-FEDRA'),
('RETOMAR', 'pastilla 21 días')
);

update public.plantillas_receta set activo = false
where origen_actualizacion = 'archivo-20261008' and (categoria, nombre) in (
('FASE 1', 'COMBINADO 2 PASTILLAS FASE 1'),
('FASE 1', 'COMBINADO 21 DIAS'),
('FASE 1', 'COMBINADO FASE 1-FEDRA'),
('FASE 1', 'KWIKPEN 2.5 COMBINADO FASE 1'),
('FASE 1', 'KWIKPEN 2.5 mg'),
('FASE 1', 'NOTA'),
('FASE 1', 'PASTILLA FASE 1'),
('FASE 1', 'PASTILLA FASE 1 15 DIAS'),
('FASE 1', 'PASTILLA FASE 1 de 21 días'),
('FASE 1', 'RYBELSUS 3mg COMBINADO FASE 1'),
('FASE 1', 'RYBELSUS FASE 1 30 DÍAS'),
('FASE 1', 'SAXENDA FASE 1-FEDRA'),
('FASE 1', 'WEGOVY COMBINADO FASE 1'),
('FASE 1', 'WEGOVY FASE 1'),
('FASE 2', 'COMBINADO 30 DIAS FASE 3'),
('FASE 2', 'COMBINADO FASE 3 15 DIAS'),
('FASE 2', 'COMBINADO RYBELSUS 30 DIAS'),
('FASE 2', 'KWIKPEN COMBINADO FASE 3'),
('FASE 2', 'MOUNJARO COMBINADO FASE 3'),
('FASE 2', 'PASTILLAS 15 DIAS FASE 3'),
('FASE 2', 'PASTILLAS 30 DIAS FASE 3'),
('FASE 2', 'SAXENDA 3'),
('FASE 2', 'WEGOVY COMBINADO FASE 3'),
('FASE 2', 'WEGOVY FASE 3'),
('FASE 3 y 4', 'COMBINADO 15 DIAS.'),
('FASE 3 y 4', 'COMBINADO FASE 5'),
('FASE 3 y 4', 'COMBINADO RYBELSUS'),
('FASE 3 y 4', 'KWIKPEN COMBINADO FASE 5'),
('FASE 3 y 4', 'KWIKPEN FASE 5'),
('FASE 3 y 4', 'MOUNJARO COMBINADO FASE 5'),
('FASE 3 y 4', 'PASTILLAS 15 DIAS FASE 5'),
('FASE 3 y 4', 'PASTILLAS 30 DIAS FASE 5'),
('FASE 3 y 4', 'WEGOVY COMBINADO FASE 5'),
('FASE 3 y 4', 'WEGOVY FASE 5'),
('FASE 5', 'combinado 15 días-FEDRA'),
('FASE 5', 'COMBINADO 21 DÍAS-FEDRA'),
('FASE 5', 'combinado 30 días 2 pastillas-FEDRA'),
('FASE 5', 'Combinado Retomar 30 días 1 pastilla-FEDRA'),
('FASE 5', 'MOUNJARO COMBINADO RETOMAR'),
('FASE 5', 'pastilla 21 días'),
('FASE 5', 'Pastillas 30 días 2 termogenicos'),
('FASE 5', 'Retomar 30 días 1 pastilla'),
('FASE 5', 'RETOMAR RYBELSUS Pastillas 30 días'),
('FASE 5', 'Victoza 23 días'),
('FASE 5', 'WEGOVY COMBINADO RETOMAR 21 DIAS'),
('FASE 5', 'WEGOVY COMBINADO RETOMAR 30 DIAS'),
('FASE 5', 'Wikpen COMBINADO RETOMAR 30 DIAS'),
('Mantenimiento', 'Mantenimiento 1 pastilla'),
('RETOMAR', 'DESTETE COMBINADO'),
('RETOMAR', 'DESTETE COMBINADO KWIKPEN'),
('RETOMAR', 'DESTETE COMBINADO WEGOBY'),
('RETOMAR', 'DESTETE MOUNJARO'),
('RETOMAR', 'DESTETE PASTILLA'),
('RETOMAR', 'DESTETE SAXENDA')
);

insert into public.plantillas_receta
  (categoria, nombre, fases, fase_texto, items, orden, activo, origen_actualizacion)
values
  ('FASE 1', 'COMBINADO 2 PASTILLAS FASE 1', array[1]::int[], 'FASE 1: 30 días', '[{"medicamento":"Norex 50 mg","duracion_dias":null,"dosis":"1 en ayuno.","indicaciones":""},{"medicamento":"Diety Ap 20 mg","duracion_dias":null,"dosis":"1 a las 4:00 pm.","indicaciones":""},{"medicamento":"Metformina 850 mg","duracion_dias":null,"dosis":"1 después de cenar.","indicaciones":""},{"medicamento":"Saxenda (2) (27 días)","duracion_dias":27,"dosis":"1) 0.6 mg x 7 días.\n2) 1.2 mg x 7 días.\n3) 1.8 mg lo restante.","indicaciones":""}]'::jsonb, 0, true, '20261008'),
  ('FASE 1', 'COMBINADO 21 DIAS', array[1]::int[], 'FASE 1: 21 días', '[{"medicamento":"Norex 50 mg","duracion_dias":null,"dosis":"1 en ayuno.\n1/2 a las 4:00 pm.","indicaciones":""},{"medicamento":"Metformina 850 mg","duracion_dias":null,"dosis":"1 después de cenar.","indicaciones":""},{"medicamento":"Saxenda (2) (27 días)","duracion_dias":27,"dosis":"1) 0.6 mg x 7 días.\n2) 1.2 mg x 7 días.\n3) 1.8 mg lo restante.","indicaciones":""}]'::jsonb, 10, true, '20261008'),
  ('FASE 1', 'COMBINADO FASE 1-FEDRA', array[1]::int[], 'FASE 1: 30 días', '[{"medicamento":"Lose 2 mg","duracion_dias":null,"dosis":"1/2 en ayuno.\n1/2 a las 4:00 pm.","indicaciones":""},{"medicamento":"Metformina 850 mg","duracion_dias":null,"dosis":"1 después de cenar.","indicaciones":""},{"medicamento":"Saxenda (2) (27 días)","duracion_dias":27,"dosis":"1) 0.6 mg x 7 días.\n2) 1.2 mg x 7 días.\n3) 1.8 mg lo restante.","indicaciones":""}]'::jsonb, 20, true, '20261008'),
  ('FASE 1', 'KWIKPEN 2.5 COMBINADO FASE 1', array[1]::int[], 'FASE 1: 30 días', '[{"medicamento":"Lose 2 mg","duracion_dias":null,"dosis":"1/2 en ayuno.\n1/2 a las 4:00 pm.","indicaciones":""},{"medicamento":"Metformina 850 mg","duracion_dias":null,"dosis":"1 después de cenar.","indicaciones":""},{"medicamento":"KwikPen 2.5 mg (1) (28 días)","duracion_dias":28,"dosis":"Aplicar 2.5 mg 1 vez a la semana, vía subcutánea por 4 semanas\n- Alternar la aplicación en brazos, piernas y abdomen.\n- Repetir la dosis el mismo día de la semana a la misma hora.\n- De preferencia después del desayuno o comida.","indicaciones":""}]'::jsonb, 30, true, '20261008'),
  ('FASE 1', 'KWIKPEN 2.5 mg', array[1]::int[], 'FASE 1: 28 días', '[{"medicamento":"KwikPen 2.5 mg (1) (28 días)","duracion_dias":28,"dosis":"Aplicar 2.5 mg 1 vez a la semana, vía subcutánea por 4 semanas\n- Alternar la aplicación en brazos, piernas y abdomen.\n- Repetir la dosis el mismo día de la semana a la misma hora.\n- Después de algún alimento.","indicaciones":""}]'::jsonb, 40, true, '20261008'),
  ('FASE 1', 'NOTA', array[1]::int[], null, '[{"medicamento":"Difenidol tabletas","duracion_dias":null,"dosis":"1 cada 12 horas por 4 días en caso de\nnáuseas molestas.","indicaciones":""},{"medicamento":"Metoclopramida 10 mg","duracion_dias":null,"dosis":"1 cada 8 horas por 5 días en caso de\neructos, gas, colitis, reflujo o malestar estomacal.","indicaciones":""},{"medicamento":"Difenidol inyectable","duracion_dias":null,"dosis":"1 ámpula dosis única vía IM en caso de vómito\nsevero.","indicaciones":""}]'::jsonb, 50, true, '20261008'),
  ('FASE 1', 'PASTILLA FASE 1', array[1]::int[], 'FASE 1: 30 días', '[{"medicamento":"Norex 50 mg","duracion_dias":null,"dosis":"1/2 en ayuno.\n1/2 a las 4:00 pm.","indicaciones":""},{"medicamento":"Metformina 850 mg","duracion_dias":null,"dosis":"1 después de cenar.","indicaciones":""}]'::jsonb, 60, true, '20261008'),
  ('FASE 1', 'PASTILLA FASE 1 15 DIAS', array[1]::int[], 'FASE 1: 15 días', '[{"medicamento":"Norex 50 mg","duracion_dias":null,"dosis":"1 en ayuno.\n1 a las 4:00 pm.","indicaciones":""},{"medicamento":"Metformina 850 mg","duracion_dias":null,"dosis":"1 después de cenar.","indicaciones":""}]'::jsonb, 70, true, '20261008'),
  ('FASE 1', 'PASTILLA FASE 1 de 21 días', array[1]::int[], 'FASE 1: 21 días', '[{"medicamento":"Lose 2 mg","duracion_dias":null,"dosis":"1 en ayuno.\n1/2 a las 4:00 pm.","indicaciones":""},{"medicamento":"Metformina 850 mg","duracion_dias":null,"dosis":"1 después de cenar.","indicaciones":""}]'::jsonb, 80, true, '20261008'),
  ('FASE 1', 'RYBELSUS 3mg COMBINADO FASE 1', array[1]::int[], 'FASE 1: 30 días', '[{"medicamento":"Diety Ap 20 mg","duracion_dias":null,"dosis":"1/2 en ayuno.\n1/2 a las 4:00 pm.","indicaciones":""},{"medicamento":"Metformina 850 mg","duracion_dias":null,"dosis":"1 después de cenar.","indicaciones":""},{"medicamento":"Rybelsus 3 mg (1) (30 días)","duracion_dias":30,"dosis":"1 diaria en ayuno, 30 minutos antes de desayunar\npor 10 días.","indicaciones":""}]'::jsonb, 90, true, '20261008'),
  ('FASE 1', 'RYBELSUS FASE 1 30 DÍAS', array[1]::int[], 'FASE 1: 30 días', '[{"medicamento":"Rybelsus 3 mg (1) (30 días)","duracion_dias":30,"dosis":"1 diaria en ayuno, 30 minutos antes de desayunar\npor 30 días.","indicaciones":""}]'::jsonb, 100, true, '20261008'),
  ('FASE 1', 'SAXENDA FASE 1-FEDRA', array[1]::int[], 'FASE 1: 27 días', '[{"medicamento":"Saxenda (1) (17 días)","duracion_dias":17,"dosis":"1) 0.6 mg x 7 días.\n2) 1.2 mg x 7 días.\n3) 1.8 mg lo restante.","indicaciones":""}]'::jsonb, 110, true, '20261008'),
  ('FASE 1', 'WEGOVY COMBINADO FASE 1', array[1]::int[], 'FASE 1: 30 días', '[{"medicamento":"Lose 2 mg","duracion_dias":null,"dosis":"1/2 en ayuno.\n1/2 a las 4:00 pm.","indicaciones":""},{"medicamento":"Metformina 850 mg","duracion_dias":null,"dosis":"1 después de cenar.","indicaciones":""},{"medicamento":"Wegovy 0.25 mg (1) (28 días)","duracion_dias":28,"dosis":"Aplicar 0.25 mg 1 vez a la semana, vía subcutánea por 4 semanas\n- Alternar la aplicación en brazos, piernas y abdomen.\n- Repetir la dosis el mismo día de la semana a la misma hora.\n- De preferencia después del desayuno o comida.","indicaciones":""}]'::jsonb, 120, true, '20261008'),
  ('FASE 1', 'WEGOVY FASE 1', array[1]::int[], 'FASE 1: 28 días', '[{"medicamento":"Wegovy 0.25 mg (1) (28 días)","duracion_dias":28,"dosis":"Aplicar 0.25 mg 1 vez a la semana, vía subcutánea por 4 semanas\n- Alternar la aplicación en brazos, piernas y abdomen.\n- Repetir la dosis el mismo día de la semana a la misma hora.\n- Después de algún alimento.","indicaciones":""}]'::jsonb, 130, true, '20261008'),
  ('FASE 2', 'COMBINADO FASE 2 15 DÍAS', array[2]::int[], 'FASE 2: 15 días', '[{"medicamento":"Norex 50 mg","duracion_dias":null,"dosis":"1 en ayuno.\n1 a las 4:00 pm.","indicaciones":""},{"medicamento":"Metformina 850 mg","duracion_dias":null,"dosis":"1 después de cenar.","indicaciones":""},{"medicamento":"Saxenda (1) (10 días)","duracion_dias":10,"dosis":"1.8 mg diarios.","indicaciones":""}]'::jsonb, 140, true, '20261008'),
  ('FASE 2', 'COMBINADO FASE 2 21 DIAS', array[2]::int[], 'FASE 2: 21 días', '[{"medicamento":"Acxion 30 mg","duracion_dias":null,"dosis":"1 en ayuno.\n1/2 a las 4:00 pm.","indicaciones":""},{"medicamento":"Metformina 850 mg","duracion_dias":null,"dosis":"1 después de cenar.","indicaciones":""},{"medicamento":"Saxenda (1) (10 días)","duracion_dias":10,"dosis":"1.8 mg diarios.","indicaciones":""}]'::jsonb, 150, true, '20261008'),
  ('FASE 2', 'COMBINADO FASE 2 de 30 días pdf', array[2]::int[], 'FASE 2: 30 días', '[{"medicamento":"Acxion 30 mg","duracion_dias":null,"dosis":"1 en ayuno.","indicaciones":""},{"medicamento":"Lose 2 mg","duracion_dias":null,"dosis":"1 a las 4:00 pm.","indicaciones":""},{"medicamento":"Metformina 850 mg","duracion_dias":null,"dosis":"1 después de cenar.","indicaciones":""},{"medicamento":"Saxenda (1) (10 días)","duracion_dias":10,"dosis":"1.8 mg diarios.","indicaciones":""}]'::jsonb, 160, true, '20261008'),
  ('FASE 2', 'KWIKPEN COMBINADO FASE 2', array[2]::int[], 'FASE 2: 21 días', '[{"medicamento":"Diety Ap 20 mg","duracion_dias":null,"dosis":"1 en ayuno.\n1/2 a las 4:00 pm.","indicaciones":""},{"medicamento":"Metformina 850 mg","duracion_dias":null,"dosis":"1 después de cenar.","indicaciones":""},{"medicamento":"KwikPen 2.5 mg (1) (28 días)","duracion_dias":28,"dosis":"Aplicar 2.5 mg 1 vez a la semana, vía subcutánea por 4 semanas\n- Alternar la aplicación en brazos, piernas y abdomen.\n- Repetir la dosis el mismo día de la semana a la misma hora.\n- De preferencia después del desayuno o comida.","indicaciones":""}]'::jsonb, 170, true, '20261008'),
  ('FASE 2', 'KWIKPEN FASE 2', array[2]::int[], 'FASE 2: 28 días', '[{"medicamento":"KwikPen 2.5 mg (1) (28 días)","duracion_dias":28,"dosis":"Aplicar 2.5 mg 1 vez a la semana, vía subcutánea por 4 semanas\n- Alternar la aplicación en brazos, piernas y abdomen.\n- Repetir la dosis el mismo día de la semana a la misma hora.\n- De preferencia después del desayuno o comida.","indicaciones":""}]'::jsonb, 180, true, '20261008'),
  ('FASE 2', 'PASTILLA FASE 2 21 DIAS', array[2]::int[], 'FASE 2: 21 días', '[{"medicamento":"Acxion 30 mg","duracion_dias":null,"dosis":"1 en ayuno.\n1/2 a las 4:00 pm.","indicaciones":""},{"medicamento":"Metformina 850 mg","duracion_dias":null,"dosis":"1 después de cenar.","indicaciones":""}]'::jsonb, 190, true, '20261008'),
  ('FASE 2', 'PASTILLA fase 2 de 15 días', array[2]::int[], 'FASE 2: 15 días', '[{"medicamento":"Norex 50 mg","duracion_dias":null,"dosis":"1 en ayuno.\n1 a las 4:00 pm.","indicaciones":""},{"medicamento":"Metformina 850 mg","duracion_dias":null,"dosis":"1 después de cenar.","indicaciones":""}]'::jsonb, 200, true, '20261008'),
  ('FASE 2', 'RYBELSUS 3', array[2]::int[], 'FASE 1: 30 días', '[{"medicamento":"Rybelsus 3 mg (1) (30 días)","duracion_dias":30,"dosis":"1 diaria en ayuno, 30 minutos antes de desayunar\npor 30 días.","indicaciones":""}]'::jsonb, 210, true, '20261008'),
  ('FASE 2', 'RYBELSUS COMBINADO 3 mg', array[2]::int[], 'FASE 2: 21 días', '[{"medicamento":"Norex 50 mg","duracion_dias":null,"dosis":"1 en ayuno.\n1/2 a las 4:00 pm.","indicaciones":""},{"medicamento":"Metformina 850 mg","duracion_dias":null,"dosis":"1 después de cenar.","indicaciones":""},{"medicamento":"Rybelsus 3 mg (1) (30 días)","duracion_dias":30,"dosis":"1 diaria en ayuno, 30 minutos antes de desayunar\npor 30 días.","indicaciones":""}]'::jsonb, 220, true, '20261008'),
  ('FASE 2', 'SAXENDA', array[2]::int[], 'FASE 2: 20 días', '[{"medicamento":"Saxenda (1) (10 días)","duracion_dias":10,"dosis":"1.8 mg. diarios.","indicaciones":""}]'::jsonb, 230, true, '20261008'),
  ('FASE 2', 'WEGOVY COMBINADO FASE 2 21 DIAS', array[2]::int[], 'FASE 2: 21 días', '[{"medicamento":"Diety Ap 20 mg","duracion_dias":null,"dosis":"1 en ayuno.\n1/2 a las 4:00 pm.","indicaciones":""},{"medicamento":"Metformina 850 mg","duracion_dias":null,"dosis":"1 después de cenar.","indicaciones":""},{"medicamento":"Wegovy 0.25 mg (1) (28 días)","duracion_dias":28,"dosis":"Aplicar 0.25 mg 1 vez a la semana, vía subcutánea por 4 semanas\n- Alternar la aplicación en brazos, piernas y abdomen.\n- Repetir la dosis el mismo día de la semana a la misma hora.\n- De preferencia después del desayuno o comida.","indicaciones":""}]'::jsonb, 240, true, '20261008'),
  ('FASE 2', 'WEGOVY FASE 2', array[2]::int[], 'FASE 2: 28 días', '[{"medicamento":"Wegovy 0.5 mg (1) (28 días)","duracion_dias":28,"dosis":"Aplicar 0.5 mg 1 vez a la semana, vía subcutánea por 4 semanas\n- Alternar la aplicación en brazos, piernas y abdomen.\n- Repetir la dosis el mismo día de la semana a la misma hora.\n- De preferencia después del desayuno o comida.","indicaciones":""}]'::jsonb, 250, true, '20261008'),
  ('FASE 3 y 4', 'COMBINADO 30 DIAS FASE 3', array[3,4]::int[], 'FASE 3: 30 días', '[{"medicamento":"Diety Ap 20 mg","duracion_dias":null,"dosis":"1 en ayuno.","indicaciones":""},{"medicamento":"Acxion 30  mg","duracion_dias":null,"dosis":"1 a las 4:00 pm.","indicaciones":""},{"medicamento":"Metformina 850 mg","duracion_dias":null,"dosis":"1 después de cenar.","indicaciones":""},{"medicamento":"Saxenda (1) (10 días)","duracion_dias":10,"dosis":"1.8 mg diarios.","indicaciones":""}]'::jsonb, 260, true, '20261008'),
  ('FASE 3 y 4', 'COMBINADO FASE 3 15 DIAS', array[3,4]::int[], 'FASE 3: 15 días', '[{"medicamento":"Norex 50 mg","duracion_dias":null,"dosis":"1 en ayuno.\n1 a las 4:00 pm.","indicaciones":""},{"medicamento":"Metformina 850 mg","duracion_dias":null,"dosis":"1 después de cenar.","indicaciones":""},{"medicamento":"Saxenda (1) (10 días)","duracion_dias":10,"dosis":"1.8 mg diarios.","indicaciones":""}]'::jsonb, 270, true, '20261008'),
  ('FASE 3 y 4', 'COMBINADO RYBELSUS 30 DIAS', array[3,4]::int[], 'FASE 3: 30 días', '[{"medicamento":"Acxion 30 mg","duracion_dias":null,"dosis":"1 en ayuno.","indicaciones":""},{"medicamento":"Diety Ap 20 mg","duracion_dias":null,"dosis":"1 a las 4:00 pm.","indicaciones":""},{"medicamento":"Metformina 850 mg","duracion_dias":null,"dosis":"1 después de cenar.","indicaciones":""},{"medicamento":"Rybelsus 7 mg (1) (30 días)","duracion_dias":30,"dosis":"1 diaria en ayuno, 30 minutos antes antes de desayunar\npor 30 días.","indicaciones":""}]'::jsonb, 280, true, '20261008'),
  ('FASE 3 y 4', 'KWIKPEN COMBINADO FASE 3', array[3,4]::int[], 'FASE 3: 30 días', '[{"medicamento":"Diety Ap 20 mg","duracion_dias":null,"dosis":"1 en ayuno.","indicaciones":""},{"medicamento":"Acxion 30  mg","duracion_dias":null,"dosis":"1 a las 4:00 pm.","indicaciones":""},{"medicamento":"Metformina 850 mg","duracion_dias":null,"dosis":"1 después de cenar.","indicaciones":""},{"medicamento":"KwikPen 2.5 mg (1) (28 días)","duracion_dias":28,"dosis":"Aplicar 2.5 mg 1 vez a la semana, vía subcutánea por 4 semanas.\n- Alternar la aplicación en brazos, piernas y abdomen.\n- Repetir la dosis el mismo día de la semana a la misma hora.\n- Después de algún alimento.","indicaciones":""}]'::jsonb, 290, true, '20261008'),
  ('FASE 3 y 4', 'MOUNJARO COMBINADO FASE 3', array[3,4]::int[], 'FASE 3: 30 días', '[{"medicamento":"Acxion 30 mg","duracion_dias":null,"dosis":"1 en ayuno.","indicaciones":""},{"medicamento":"Diety Ap 20 mg","duracion_dias":null,"dosis":"1 a las 4:00 pm.","indicaciones":""},{"medicamento":"Metformina 850 mg","duracion_dias":null,"dosis":"1 después de cenar.","indicaciones":""},{"medicamento":"Mounjaro 2.5 mg. (1) (7 días)","duracion_dias":7,"dosis":"Aplicar 2.5 mg 1 vez a la semana, vía subcutánea,\npor 4 semanas, con jeringa de insulina.\n- Alternar la aplicación en brazo, piernas y abdomen.\n- Repetir la dosis el mismo día de la semana a la misma hora.\n- De preferencia después del desayuno o comida.","indicaciones":""}]'::jsonb, 300, true, '20261008'),
  ('FASE 3 y 4', 'PASTILLAS 15 DIAS FASE 3', array[3,4]::int[], 'FASE 3: 15 días', '[{"medicamento":"Norex 50 mg","duracion_dias":null,"dosis":"1 en ayuno.\n1 a las 4:00 pm.","indicaciones":""},{"medicamento":"Metformina 850 mg","duracion_dias":null,"dosis":"1 después de cenar.","indicaciones":""}]'::jsonb, 310, true, '20261008'),
  ('FASE 3 y 4', 'PASTILLAS 30 DIAS FASE 3', array[3,4]::int[], 'FASE 3: 30 días', '[{"medicamento":"Norex 50 mg","duracion_dias":null,"dosis":"1 en ayuno.","indicaciones":""},{"medicamento":"Lose 2 mg","duracion_dias":null,"dosis":"1 a las 4:00 pm.","indicaciones":""},{"medicamento":"Metformina 850 mg","duracion_dias":null,"dosis":"1 después de cenar.","indicaciones":""}]'::jsonb, 320, true, '20261008'),
  ('FASE 3 y 4', 'SAXENDA 3', array[3,4]::int[], 'FASE 3: 20 días', '[{"medicamento":"Saxenda (1) (10 días)","duracion_dias":10,"dosis":"1.8 mg diarios.","indicaciones":""}]'::jsonb, 330, true, '20261008'),
  ('FASE 3 y 4', 'WEGOVY COMBINADO FASE 3', array[3,4]::int[], 'FASE 3: 30 días', '[{"medicamento":"Diety Ap 20 mg","duracion_dias":null,"dosis":"1 en ayuno.","indicaciones":""},{"medicamento":"Acxion 30  mg","duracion_dias":null,"dosis":"1 a las 4:00 pm.","indicaciones":""},{"medicamento":"Metformina 850 mg","duracion_dias":null,"dosis":"1 después de cenar.","indicaciones":""},{"medicamento":"Wegovy 0.25 mg (1) (28 días)","duracion_dias":28,"dosis":"Aplicar 0.25 mg 1 vez a la semana, vía subcutánea por 4 semanas.\n- Alternar aplicación en brazos, piernas y abdomen.\n- Repetir la dosis el mismo día de la semana a la misma hora.\n- Después de algún alimento.","indicaciones":""}]'::jsonb, 340, true, '20261008'),
  ('FASE 3 y 4', 'WEGOVY FASE 3', array[3,4]::int[], 'FASE 3: 28 días', '[{"medicamento":"Wegovy 0.25 mg (1) (28 días)","duracion_dias":28,"dosis":"Aplicar 0.25 mg 1 vez a la semana, vía subcutánea por 4 semanas\n- Alternar la aplicacion en brazos, piernas y abdomen.\n- Repetir la dosis el mismo día de la semana a la misma hora.\n- Después de algún alimento.","indicaciones":""}]'::jsonb, 350, true, '20261008'),
  ('FASE 5', 'COMBINADO 15 DIAS.', array[5]::int[], 'FASE 5: 15 días', '[{"medicamento":"Norex 50 mg","duracion_dias":null,"dosis":"1 en ayuno.\n1 a las 4:00 pm.","indicaciones":""},{"medicamento":"Metformina 850 mg","duracion_dias":null,"dosis":"1 cada 12 horas, después del desayuno y la cena.\nEn caso de no tolerar, continuar con 1 después de cenar.","indicaciones":""},{"medicamento":"Saxenda (1) (10 días)","duracion_dias":10,"dosis":"1.8 mg diarios.","indicaciones":""}]'::jsonb, 360, true, '20261008'),
  ('FASE 5', 'COMBINADO FASE 5', array[5]::int[], 'FASE 5: 30 días', '[{"medicamento":"Diety Ap 20 mg","duracion_dias":null,"dosis":"1 en ayuno.","indicaciones":""},{"medicamento":"Acxion 30  mg","duracion_dias":null,"dosis":"1 a las 4:00 pm.","indicaciones":""},{"medicamento":"Metformina 850 mg","duracion_dias":null,"dosis":"1 cada 12 horas, después del desayuno y la cena.\nEn caso de no tolerar, continuar con 1 después de cenar.","indicaciones":""},{"medicamento":"Saxenda (1) (10 días)","duracion_dias":10,"dosis":"1.8 mg diarios.","indicaciones":""}]'::jsonb, 370, true, '20261008'),
  ('FASE 5', 'COMBINADO RYBELSUS', array[5]::int[], 'FASE 5: 30 días', '[{"medicamento":"Diety Ap 20 mg","duracion_dias":null,"dosis":"1 en ayuno.","indicaciones":""},{"medicamento":"Acxion 30  mg","duracion_dias":null,"dosis":"1 a las 4:00 pm.","indicaciones":""},{"medicamento":"Metformina 850 mg","duracion_dias":null,"dosis":"1 cada 12 horas, después del desayuno y la cena.\nEn caso de no tolerar, continuar con 1 después de cenar.","indicaciones":""},{"medicamento":"Rybelsus 7 mg (1) (30 días)","duracion_dias":30,"dosis":"1 diaria en ayuno, 30 minutos antes antes de desayunar\npor 30 días.","indicaciones":""}]'::jsonb, 380, true, '20261008'),
  ('FASE 5', 'KWIKPEN COMBINADO FASE 5', array[5]::int[], 'FASE 5: 30 días', '[{"medicamento":"Diety Ap 20 mg","duracion_dias":null,"dosis":"1 en ayuno.","indicaciones":""},{"medicamento":"Acxion 30  mg","duracion_dias":null,"dosis":"1 a las 4:00 pm.","indicaciones":""},{"medicamento":"Metformina 850 mg","duracion_dias":null,"dosis":"1 cada 12 horas, después del desayuno y la cena.\nEn caso de no tolerar, continuar con 1 después de cenar.","indicaciones":""},{"medicamento":"KwikPen 2.5 mg (1) (28 días)","duracion_dias":28,"dosis":"Aplicar 2.5 mg 1 vez a la semana, vía subcutánea por 4 semanas.\n- Alternar la aplicación en brazos, piernas y abdomen.\n- Repetir la dosis el mismo día de la semana a la misma hora.\n- Después de algún alimento.","indicaciones":""}]'::jsonb, 390, true, '20261008'),
  ('FASE 5', 'KWIKPEN FASE 5', array[5]::int[], 'FASE 5: 30 días', '[{"medicamento":"KwikPen 2.5 mg (1) (28 días)","duracion_dias":28,"dosis":"Aplicar 2.5 mg 1 vez a la semana, vía subcutánea por 4 semanas.\n- Alternar la aplicación en brazos, piernas y abdomen.\n- Repetir la dosis el mismo día de la semana a la misma hora.\n- Después de algún alimento.","indicaciones":""}]'::jsonb, 400, true, '20261008'),
  ('FASE 5', 'MOUNJARO COMBINADO FASE 5', array[5]::int[], 'FASE 5: 30 días', '[{"medicamento":"Diety Ap 20 mg","duracion_dias":null,"dosis":"1 en ayuno.","indicaciones":""},{"medicamento":"Lose 2 mg","duracion_dias":null,"dosis":"1 a las 4:00 pm.","indicaciones":""},{"medicamento":"Metformina 850 mg","duracion_dias":null,"dosis":"1 cada 12 horas, después del desayuno y la cena.\nEn caso de no tolerar, continuar con 1 después de cenar.","indicaciones":""},{"medicamento":"Mounjaro 2.5 mg. (1) (7 días)","duracion_dias":7,"dosis":"Aplicar 2.5 mg 1 vez a la semana, vía subcutánea,\npor 4 semanas, con jeringa de insulina.\n- Alternar la aplicación en brazo, piernas y abdomen.\n- Repetir la dosis el mismo día de la semana a la misma hora.\n- De preferencia después del desayuno o comida.","indicaciones":""}]'::jsonb, 410, true, '20261008'),
  ('FASE 5', 'PASTILLAS 15 DIAS FASE 5', array[5]::int[], 'FASE 5: 15 días', '[{"medicamento":"Norex 50 mg","duracion_dias":null,"dosis":"1 en ayuno.\n1 a las 4:00 pm.","indicaciones":""},{"medicamento":"Metformina 850 mg","duracion_dias":null,"dosis":"1 cada 12 horas, después del desayuno y la cena.\nEn caso de no tolerar, continuar con 1 después de cenar.","indicaciones":""}]'::jsonb, 420, true, '20261008'),
  ('FASE 5', 'PASTILLAS 30 DIAS FASE 5', array[5]::int[], 'FASE 5: 30 días', '[{"medicamento":"Norex 50 mg","duracion_dias":null,"dosis":"1 en ayuno.","indicaciones":""},{"medicamento":"Lose 2 mg","duracion_dias":null,"dosis":"1 a las 4:00 pm.","indicaciones":""},{"medicamento":"Metformina 850 mg","duracion_dias":null,"dosis":"1 cada 12 horas, después del desayuno y la cena.\nEn caso de no tolerar, continuar con 1 después de cenar.","indicaciones":""}]'::jsonb, 430, true, '20261008'),
  ('FASE 5', 'WEGOVY COMBINADO FASE 5', array[5]::int[], 'FASE 5: 30 días', '[{"medicamento":"Diety Ap 20 mg","duracion_dias":null,"dosis":"1 en ayuno.","indicaciones":""},{"medicamento":"Lose 2 mg","duracion_dias":null,"dosis":"1 a las 4:00 pm.","indicaciones":""},{"medicamento":"Metformina 850 mg","duracion_dias":null,"dosis":"1 cada 12 horas, después del desayuno y la cena.\nEn caso de no tolerar, continuar con 1 después de cenar.","indicaciones":""},{"medicamento":"Wegovy 0.25 mg (1) (28 días)","duracion_dias":28,"dosis":"Aplicar 0.25 mg 1 vez a la semana, vía subcutánea por 4 semanas\n- Alternar la aplicación en brazos, piernas y abdomen.\n- Repetir la dosis el mismo día de la semana a la misma hora.\n- De preferencia después del desayuno o comida.","indicaciones":""}]'::jsonb, 440, true, '20261008'),
  ('FASE 5', 'WEGOVY FASE 5', array[5]::int[], 'FASE 5: 28 días', '[{"medicamento":"Wegovy 0.25 mg (1) (28 días)","duracion_dias":28,"dosis":"Aplicar 0.25 mg 1 vez a la semana, vía subcutánea por 4 semanas\n- Alternar la aplicación en brazos, piernas y abdomen.\n- Repetir la dosis el mismo día de la semana a la misma hora.\n- De preferencia después del desayuno o comida.","indicaciones":""}]'::jsonb, 450, true, '20261008'),
  ('Mantenimiento', 'Mantenimiento 1 pastilla', array[]::int[], 'Mantenimiento', '[{"medicamento":"Acxion 30 mg","duracion_dias":null,"dosis":"1 en ayuno cada 48 hrs. hasta terminar.","indicaciones":""},{"medicamento":"Metformina 850 mg","duracion_dias":null,"dosis":"1 después de cenar.","indicaciones":""}]'::jsonb, 460, true, '20261008'),
  ('RETOMAR', 'combinado 15 días-FEDRA', array[]::int[], 'FASE 1: 15 días', '[{"medicamento":"Norex 50 mg","duracion_dias":null,"dosis":"1 en ayuno.\n1 a las 4:00 pm.","indicaciones":""},{"medicamento":"Metformina 850 mg","duracion_dias":null,"dosis":"1 después de cenar.","indicaciones":""},{"medicamento":"Victoza (1) (13 días)","duracion_dias":13,"dosis":"1) 0.6 mg x 3 días.\n2) 1.2 mg x 3 días.\n3) 1.8 mg lo restante.","indicaciones":""}]'::jsonb, 470, true, '20261008'),
  ('RETOMAR', 'COMBINADO 21 DÍAS-FEDRA', array[]::int[], 'FASE 1: 21 días', '[{"medicamento":"Diety Ap 20 mg","duracion_dias":null,"dosis":"1 en ayuno.\n1/2 a las 4:00 pm.","indicaciones":""},{"medicamento":"Metformina 850 mg","duracion_dias":null,"dosis":"1 después de cenar.","indicaciones":""},{"medicamento":"Saxenda (1) (13 días)","duracion_dias":13,"dosis":"1) 0.6 mg x 3 días.\n2) 1.2 mg x 3 días.\n3) 1.8 mg lo restante.","indicaciones":""}]'::jsonb, 480, true, '20261008'),
  ('RETOMAR', 'combinado 30 días 2 pastillas-FEDRA', array[]::int[], 'FASE 1: 30 días', '[{"medicamento":"Norex 50 mg","duracion_dias":null,"dosis":"1 en ayuno.","indicaciones":""},{"medicamento":"Diety Ap 20 mg","duracion_dias":null,"dosis":"1 a las 4:00 pm.","indicaciones":""},{"medicamento":"Metformina 850 mg","duracion_dias":null,"dosis":"1 después de cenar.","indicaciones":""},{"medicamento":"Saxenda (1) (13 días)","duracion_dias":13,"dosis":"1) 0.6 mg x 3 días.\n2) 1.2 mg x 3 días.\n3) 1.8 mg lo restante.","indicaciones":""}]'::jsonb, 490, true, '20261008'),
  ('RETOMAR', 'Combinado Retomar 30 días 1 pastilla-FEDRA', array[]::int[], 'FASE 1: 30 días', '[{"medicamento":"Diety Ap 20 mg","duracion_dias":null,"dosis":"1/2 en ayuno.\n1/2 a las 4:00 pm.","indicaciones":""},{"medicamento":"Metformina 850 mg","duracion_dias":null,"dosis":"1 después de cenar.","indicaciones":""},{"medicamento":"Victoza (1) (13 días)","duracion_dias":13,"dosis":"1) 0.6 mg x 3 días.\n2) 1.2 mg x 3 días.\n3) 1.8 mg lo restante.","indicaciones":""}]'::jsonb, 500, true, '20261008'),
  ('RETOMAR', 'MOUNJARO COMBINADO RETOMAR', array[]::int[], 'FASE 1: 21 días', '[{"medicamento":"Diety Ap 20 mg","duracion_dias":null,"dosis":"1 en ayuno.\n1/2 a las 4:00 pm.","indicaciones":""},{"medicamento":"Metformina 850 mg","duracion_dias":null,"dosis":"1 después de cenar.","indicaciones":""},{"medicamento":"Mounjaro 2.5 mg. (1) (28 días)","duracion_dias":28,"dosis":"Aplicar 2.5 mg 1 vez a la semana, vía subcutánea,\npor 4 semanas, con jeringa de insulina.\n- Alternar la aplicación en brazo, piernas y abdomen.\n- Repetir la dosis el mismo día de la semana a la misma hora.\n- De preferencia después del desayuno o comida.","indicaciones":""}]'::jsonb, 510, true, '20261008'),
  ('RETOMAR', 'pastilla 21 días', array[]::int[], 'FASE 1: 21 días', '[{"medicamento":"Norex 50 mg","duracion_dias":null,"dosis":"1 en ayuno.\n1/2 a las 4:00 pm.","indicaciones":""},{"medicamento":"Metformina 850 mg","duracion_dias":null,"dosis":"1 después de cenar.","indicaciones":""}]'::jsonb, 520, true, '20261008'),
  ('RETOMAR', 'Pastillas 30 días 2 termogenicos', array[]::int[], 'FASE 1: 30 días', '[{"medicamento":"Lose 20 mg","duracion_dias":null,"dosis":"1 en ayuno.","indicaciones":""},{"medicamento":"Norex 50 mg","duracion_dias":null,"dosis":"1 a las 4:00 pm.","indicaciones":""},{"medicamento":"Metformina 850 mg","duracion_dias":null,"dosis":"1 después de cenar.","indicaciones":""}]'::jsonb, 530, true, '20261008'),
  ('RETOMAR', 'Retomar 30 días 1 pastilla', array[]::int[], 'FASE 1: 30 días', '[{"medicamento":"Diety Ap 20 mg","duracion_dias":null,"dosis":"1/2 en ayuno.\n1/2 a las 4:00 pm.","indicaciones":""},{"medicamento":"Metformina 850 mg","duracion_dias":null,"dosis":"1 después de cenar.","indicaciones":""}]'::jsonb, 540, true, '20261008'),
  ('RETOMAR', 'RETOMAR RYBELSUS Pastillas 30 días', array[]::int[], 'FASE 1: 30 días', '[{"medicamento":"Lose 20 mg","duracion_dias":null,"dosis":"1 en ayuno.","indicaciones":""},{"medicamento":"Norex 50 mg","duracion_dias":null,"dosis":"1 a las 4:00 pm.","indicaciones":""},{"medicamento":"Metformina 850 mg","duracion_dias":null,"dosis":"1 después de cenar.","indicaciones":""},{"medicamento":"Rybelsus 7 mg (1) (30 días)","duracion_dias":30,"dosis":"1 diaria en ayuno, 30 minutos antes de desayunar\npor 30 días.","indicaciones":""}]'::jsonb, 550, true, '20261008'),
  ('RETOMAR', 'Saxenda 23 días', array[]::int[], 'FASE 1: 23 días', '[{"medicamento":"Saxenda (1) (13 días)","duracion_dias":13,"dosis":"1) 0.6 mg x 3 días.\n2) 1.2 mg x 3 días.\n3) 1.8 mg lo restante.","indicaciones":""}]'::jsonb, 560, true, '20261008'),
  ('RETOMAR', 'Victoza 23 días', array[]::int[], 'FASE 1: 23 días', '[{"medicamento":"Victoza (1) (13 días)","duracion_dias":13,"dosis":"1) 0.6 mg x 3 días.\n2) 1.2 mg x 3 días.\n3) 1.8 mg lo restante.","indicaciones":""}]'::jsonb, 570, true, '20261008'),
  ('RETOMAR', 'WEGOVY COMBINADO RETOMAR 21 DIAS', array[]::int[], 'FASE 1: 21 días', '[{"medicamento":"Lose 2 mg","duracion_dias":null,"dosis":"1 en ayuno.\n1/2 a las 4:00 pm.","indicaciones":""},{"medicamento":"Metformina 850 mg","duracion_dias":null,"dosis":"1 después de cenar.","indicaciones":""},{"medicamento":"Wegovy 0.25 mg (1) (28 días)","duracion_dias":28,"dosis":"Aplicar 0.25 mg 1 vez a la semana, vía subcutánea por 4 semanas\n- Alternar la aplicación en brazos, piernas y abdomen.\n- Repetir la dosis el mismo día de la semana a la misma hora.\n- De preferencia después del desayuno o comida.","indicaciones":""}]'::jsonb, 580, true, '20261008'),
  ('RETOMAR', 'WEGOVY COMBINADO RETOMAR 30 DIAS', array[]::int[], 'FASE 1: 30 días', '[{"medicamento":"Lose 2 mg","duracion_dias":null,"dosis":"1 en ayuno.","indicaciones":""},{"medicamento":"Norex 50 mg","duracion_dias":null,"dosis":"1 a las 4:00 pm.","indicaciones":""},{"medicamento":"Metformina 850 mg","duracion_dias":null,"dosis":"1 después de cenar.","indicaciones":""},{"medicamento":"Wegovy 0.25 mg (1) (28 días)","duracion_dias":28,"dosis":"Aplicar 0.25 mg 1 vez a la semana, vía subcutánea por 4 semanas\n- Alternar la aplicación en brazos, piernas y abdomen.\n- Repetir la dosis el mismo día de la semana a la misma hora.\n- De preferencia después del desayuno o comida.","indicaciones":""}]'::jsonb, 590, true, '20261008'),
  ('RETOMAR', 'Wikpen COMBINADO RETOMAR 30 DIAS', array[]::int[], 'FASE 1: 30 días', '[{"medicamento":"Lose 2 mg","duracion_dias":null,"dosis":"1 en ayuno.","indicaciones":""},{"medicamento":"Norex 50 mg","duracion_dias":null,"dosis":"1 a las 4:00 pm.","indicaciones":""},{"medicamento":"Metformina 850 mg","duracion_dias":null,"dosis":"1 después de cenar.","indicaciones":""},{"medicamento":"KwikPen 2.5mg (1) (28 días)","duracion_dias":28,"dosis":"Aplicar 2.5 mg 1 vez a la semana, vía subcutánea por 4 semanas\n- Alternar la aplicación en brazos, piernas y abdomen.\n- Repetir la dosis el mismo día de la semana a la misma hora.\n- De preferencia después del desayuno o comida.","indicaciones":""}]'::jsonb, 600, true, '20261008')
on conflict (categoria, nombre) do update set
  fases = excluded.fases,
  fase_texto = excluded.fase_texto,
  items = excluded.items,
  orden = excluded.orden,
  activo = true,
  origen_actualizacion = '20261008'
where plantillas_receta.origen_actualizacion is distinct from '20261008';

do $$
declare
  activas int;
  vacias int;
begin
  select count(*) into activas from public.plantillas_receta where origen_actualizacion = '20261008';
  select count(*) into vacias
  from public.plantillas_receta
  where activo and (jsonb_typeof(items) <> 'array' or jsonb_array_length(items) = 0);
  if activas <> 61 or vacias <> 0 then
    raise exception 'Actualización de plantillas incompleta: activas=%, vacias=%', activas, vacias;
  end if;
end $$;

commit;
