-- ============================================================================
-- Plantillas de receta por fase (reunión del 15 de septiembre de 2026).
--
-- Mayira entregó 55 recetarios en PDF organizados en carpetas por fase. Aquí
-- quedan como plantillas seleccionables: Fernanda elige la categoría, elige la
-- combinación y la receta llega precargada, que es justo lo que hoy resuelve
-- copiando y pegando de archivos sueltos.
--
-- Dos cosas del material original que NO se corrigen aquí a propósito:
--
--  1. La carpeta y la etiqueta impresa no coinciden, y es sistemático: las diez
--     hojas de "FASE 2" dicen FASE 3, las diez de "FASE 3 y 4" dicen FASE 5 y
--     las trece de "FASE 5" dicen FASE 1. Se guardan las dos: `categoria` es la
--     carpeta y `fase_texto` es lo que dice la hoja. La pantalla avisa cuando
--     difieren. Cuál manda lo decide el consultorio, no el importador.
--
--  2. "DESTETE COMBINADO WEGOBY" lista Wegovy 0.5 mg y Wegovy 0.25 mg, y solo
--     la segunda trae dosis. Se respeta tal cual viene.
--
-- Se excluyeron el recetario en blanco y los datos de una paciente que habían
-- quedado escritos sobre el membrete de una de las hojas.
-- ============================================================================

create table if not exists plantillas_receta (
  id          uuid primary key default gen_random_uuid(),
  categoria   text not null,
  nombre      text not null,
  fases       int[] not null default '{}',
  fase_texto  text,
  items       jsonb not null default '[]'::jsonb,
  orden       int not null default 0,
  activo      boolean not null default true,
  creado_en   timestamptz not null default now()
);

comment on table plantillas_receta is 'Combinaciones prearmadas de la doctora, por fase. Editables sin programador.';
comment on column plantillas_receta.categoria is 'Carpeta de origen del material: FASE 1, FASE 2, FASE 3 y 4, FASE 5, Mantenimiento, RETOMAR.';
comment on column plantillas_receta.fase_texto is 'Etiqueta tal como viene impresa en la hoja. Puede no coincidir con la categoría.';

create unique index if not exists plantillas_receta_categoria_nombre
  on plantillas_receta (categoria, nombre);

alter table plantillas_receta enable row level security;

drop policy if exists "plantillas_lectura" on plantillas_receta;
create policy "plantillas_lectura" on plantillas_receta
  for select using (current_rol() is not null);

drop policy if exists "plantillas_escritura" on plantillas_receta;
create policy "plantillas_escritura" on plantillas_receta
  for all using (current_rol()::text in ('admin', 'doctora', 'gerente'))
  with check (current_rol()::text in ('admin', 'doctora', 'gerente'));

insert into plantillas_receta (categoria, nombre, fases, fase_texto, items, orden) values
  ('FASE 1', 'COMBINADO 2 PASTILLAS FASE 1', array[1]::int[], 'FASE 1: 30 días', '[{"medicamento":"Norex 50 mg","dosis":"1 en ayuno.","duracion_dias":null,"indicaciones":""},{"medicamento":"Diety Ap 20 mg","dosis":"1 a las 4:00 pm.","duracion_dias":null,"indicaciones":""},{"medicamento":"Metformina 850 mg","dosis":"1 después de cenar.","duracion_dias":null,"indicaciones":""},{"medicamento":"Saxenda (2) (27 días)","dosis":"1) 0.6 mg x 7 días.\n2) 1.2 mg x 7 días.\n3) 1.8 mg lo restante.","duracion_dias":27,"indicaciones":""}]'::jsonb, 0),
  ('FASE 1', 'COMBINADO 21 DIAS', array[1]::int[], 'FASE 1: 21 días', '[{"medicamento":"Norex 50 mg","dosis":"1 en ayuno.\n1/2 a las 4:00 pm.","duracion_dias":null,"indicaciones":""},{"medicamento":"Metformina 850 mg","dosis":"1 después de cenar.","duracion_dias":null,"indicaciones":""},{"medicamento":"Saxenda (2) (27 días)","dosis":"1) 0.6 mg x 7 días.\n2) 1.2 mg x 7 días.\n3) 1.8 mg lo restante.","duracion_dias":27,"indicaciones":""}]'::jsonb, 10),
  ('FASE 1', 'COMBINADO FASE 1-FEDRA', array[1]::int[], 'FASE 1: 30 días', '[{"medicamento":"Lose 2 mg","dosis":"1/2 en ayuno.\n1/2 a las 4:00 pm.","duracion_dias":null,"indicaciones":""},{"medicamento":"Metformina 850 mg","dosis":"1 después de cenar.","duracion_dias":null,"indicaciones":""},{"medicamento":"Saxenda (2) (27 días)","dosis":"1) 0.6 mg x 7 días.\n2) 1.2 mg x 7 días.\n3) 1.8 mg lo restante.","duracion_dias":27,"indicaciones":""}]'::jsonb, 20),
  ('FASE 1', 'KWIKPEN 2.5 COMBINADO FASE 1', array[1]::int[], 'FASE 1: 30 días', '[{"medicamento":"Lose 2 mg","dosis":"1/2 en ayuno.\n1/2 a las 4:00 pm.","duracion_dias":null,"indicaciones":""},{"medicamento":"Metformina 850 mg","dosis":"1 después de cenar.","duracion_dias":null,"indicaciones":""},{"medicamento":"KwikPen 2.5 mg (1) (28 días)","dosis":"Aplicar 2.5 mg 1 vez a la semana, vía subcutánea por 4 semanas\n- Alternar la aplicación en brazos, piernas y abdomen.\n- Repetir la dosis el mismo día de la semana a la misma hora.\n- De preferencia después del desayuno o comida.","duracion_dias":28,"indicaciones":""}]'::jsonb, 30),
  ('FASE 1', 'KWIKPEN 2.5 mg', array[1]::int[], 'FASE 1: 28 días', '[{"medicamento":"KwikPen 2.5 mg (1) (28 días)","dosis":"Aplicar 2.5 mg 1 vez a la semana, vía subcutánea por 4 semanas\n- Alternar la aplicación en brazos, piernas y abdomen.\n- Repetir la dosis el mismo día de la semana a la misma hora.\n- Después de algún alimento.","duracion_dias":28,"indicaciones":""}]'::jsonb, 40),
  ('FASE 1', 'NOTA', array[1]::int[], null, '[{"medicamento":"Difenidol tabletas","dosis":"1 cada 12 horas por 4 días en caso de\nnáuseas molestas.","duracion_dias":null,"indicaciones":""},{"medicamento":"Metoclopramida 10 mg","dosis":"1 cada 8 horas por 5 días en caso de\neructos, gas, colitis, reflujo o malestar estomacal.","duracion_dias":null,"indicaciones":""},{"medicamento":"Difenidol inyectable","dosis":"1 ámpula dosis única vía IM en caso de vómito\nsevero.","duracion_dias":null,"indicaciones":""}]'::jsonb, 50),
  ('FASE 1', 'PASTILLA FASE 1', array[1]::int[], 'FASE 1: 30 días', '[{"medicamento":"Norex 50 mg","dosis":"1/2 en ayuno.\n1/2 a las 4:00 pm.","duracion_dias":null,"indicaciones":""},{"medicamento":"Metformina 850 mg","dosis":"1 después de cenar.","duracion_dias":null,"indicaciones":""}]'::jsonb, 60),
  ('FASE 1', 'PASTILLA FASE 1 15 DIAS', array[1]::int[], 'FASE 1: 15 días', '[{"medicamento":"Norex 50 mg","dosis":"1 en ayuno.\n1 a las 4:00 pm.","duracion_dias":null,"indicaciones":""},{"medicamento":"Metformina 850 mg","dosis":"1 después de cenar.","duracion_dias":null,"indicaciones":""}]'::jsonb, 70),
  ('FASE 1', 'PASTILLA FASE 1 de 21 días', array[1]::int[], 'FASE 1: 21 días', '[{"medicamento":"Lose 2 mg","dosis":"1 en ayuno.\n1/2 a las 4:00 pm.","duracion_dias":null,"indicaciones":""},{"medicamento":"Metformina 850 mg","dosis":"1 después de cenar.","duracion_dias":null,"indicaciones":""}]'::jsonb, 80),
  ('FASE 1', 'RYBELSUS 3mg COMBINADO FASE 1', array[1]::int[], 'FASE 1: 30 días', '[{"medicamento":"Diety Ap 20 mg","dosis":"1/2 en ayuno.\n1/2 a las 4:00 pm.","duracion_dias":null,"indicaciones":""},{"medicamento":"Metformina 850 mg","dosis":"1 después de cenar.","duracion_dias":null,"indicaciones":""},{"medicamento":"Rybelsus 3 mg (1) (30 días)","dosis":"1 diaria en ayuno, 30 minutos antes de desayunar\npor 10 días.","duracion_dias":30,"indicaciones":""}]'::jsonb, 90),
  ('FASE 1', 'RYBELSUS FASE 1 30 DÍAS', array[1]::int[], 'FASE 1: 30 días', '[{"medicamento":"Rybelsus 3 mg (1) (30 días)","dosis":"1 diaria en ayuno, 30 minutos antes de desayunar\npor 30 días.","duracion_dias":30,"indicaciones":""}]'::jsonb, 100),
  ('FASE 1', 'SAXENDA FASE 1-FEDRA', array[1]::int[], 'FASE 1: 27 días', '[{"medicamento":"Saxenda (1) (17 días)","dosis":"1) 0.6 mg x 7 días.\n2) 1.2 mg x 7 días.\n3) 1.8 mg lo restante.","duracion_dias":17,"indicaciones":""}]'::jsonb, 110),
  ('FASE 1', 'WEGOVY COMBINADO FASE 1', array[1]::int[], 'FASE 1: 30 días', '[{"medicamento":"Lose 2 mg","dosis":"1/2 en ayuno.\n1/2 a las 4:00 pm.","duracion_dias":null,"indicaciones":""},{"medicamento":"Metformina 850 mg","dosis":"1 después de cenar.","duracion_dias":null,"indicaciones":""},{"medicamento":"Wegovy 0.25 mg (1) (28 días)","dosis":"Aplicar 0.25 mg 1 vez a la semana, vía subcutánea por 4 semanas\n- Alternar la aplicación en brazos, piernas y abdomen.\n- Repetir la dosis el mismo día de la semana a la misma hora.\n- De preferencia después del desayuno o comida.","duracion_dias":28,"indicaciones":""}]'::jsonb, 120),
  ('FASE 1', 'WEGOVY FASE 1', array[1]::int[], 'FASE 1: 28 días', '[{"medicamento":"Wegovy 0.25 mg (1) (28 días)","dosis":"Aplicar 0.25 mg 1 vez a la semana, vía subcutánea por 4 semanas\n- Alternar la aplicación en brazos, piernas y abdomen.\n- Repetir la dosis el mismo día de la semana a la misma hora.\n- Después de algún alimento.","duracion_dias":28,"indicaciones":""}]'::jsonb, 130),
  ('FASE 2', 'COMBINADO 30 DIAS FASE 3', array[2]::int[], 'FASE 3: 30 días', '[{"medicamento":"Diety Ap 20 mg","dosis":"1 en ayuno.","duracion_dias":null,"indicaciones":""},{"medicamento":"Acxion 30 mg","dosis":"1 a las 4:00 pm.","duracion_dias":null,"indicaciones":""},{"medicamento":"Metformina 850 mg","dosis":"1 después de cenar.","duracion_dias":null,"indicaciones":""},{"medicamento":"Saxenda (1) (10 días)","dosis":"1.8 mg diarios.","duracion_dias":10,"indicaciones":""}]'::jsonb, 140),
  ('FASE 2', 'COMBINADO FASE 3 15 DIAS', array[2]::int[], 'FASE 3: 15 días', '[{"medicamento":"Norex 50 mg","dosis":"1 en ayuno.\n1 a las 4:00 pm.","duracion_dias":null,"indicaciones":""},{"medicamento":"Metformina 850 mg","dosis":"1 después de cenar.","duracion_dias":null,"indicaciones":""},{"medicamento":"Saxenda (1) (10 días)","dosis":"1.8 mg diarios.","duracion_dias":10,"indicaciones":""}]'::jsonb, 150),
  ('FASE 2', 'COMBINADO RYBELSUS 30 DIAS', array[2]::int[], 'FASE 3: 30 días', '[{"medicamento":"Acxion 30 mg","dosis":"1 en ayuno.","duracion_dias":null,"indicaciones":""},{"medicamento":"Diety Ap 20 mg","dosis":"1 a las 4:00 pm.","duracion_dias":null,"indicaciones":""},{"medicamento":"Metformina 850 mg","dosis":"1 después de cenar.","duracion_dias":null,"indicaciones":""},{"medicamento":"Rybelsus 7 mg (1) (30 días)","dosis":"1 diaria en ayuno, 30 minutos antes antes de desayunar\npor 30 días.","duracion_dias":30,"indicaciones":""}]'::jsonb, 160),
  ('FASE 2', 'KWIKPEN COMBINADO FASE 3', array[2]::int[], 'FASE 3: 30 días', '[{"medicamento":"Diety Ap 20 mg","dosis":"1 en ayuno.","duracion_dias":null,"indicaciones":""},{"medicamento":"Acxion 30 mg","dosis":"1 a las 4:00 pm.","duracion_dias":null,"indicaciones":""},{"medicamento":"Metformina 850 mg","dosis":"1 después de cenar.","duracion_dias":null,"indicaciones":""},{"medicamento":"KwikPen 2.5 mg (1) (28 días)","dosis":"Aplicar 2.5 mg 1 vez a la semana, vía subcutánea por 4 semanas.\n- Alternar la aplicación en brazos, piernas y abdomen.\n- Repetir la dosis el mismo día de la semana a la misma hora.\n- Después de algún alimento.","duracion_dias":28,"indicaciones":""}]'::jsonb, 170),
  ('FASE 2', 'MOUNJARO COMBINADO FASE 3', array[2]::int[], 'FASE 3: 30 días', '[{"medicamento":"Acxion 30 mg","dosis":"1 en ayuno.","duracion_dias":null,"indicaciones":""},{"medicamento":"Diety Ap 20 mg","dosis":"1 a las 4:00 pm.","duracion_dias":null,"indicaciones":""},{"medicamento":"Metformina 850 mg","dosis":"1 después de cenar.","duracion_dias":null,"indicaciones":""},{"medicamento":"Mounjaro 2.5 mg. (1) (7 días)","dosis":"Aplicar 2.5 mg 1 vez a la semana, vía subcutánea,\npor 4 semanas, con jeringa de insulina.\n- Alternar la aplicación en brazo, piernas y abdomen.\n- Repetir la dosis el mismo día de la semana a la misma hora.\n- De preferencia después del desayuno o comida.","duracion_dias":7,"indicaciones":""}]'::jsonb, 180),
  ('FASE 2', 'PASTILLAS 15 DIAS FASE 3', array[2]::int[], 'FASE 3: 15 días', '[{"medicamento":"Norex 50 mg","dosis":"1 en ayuno.\n1 a las 4:00 pm.","duracion_dias":null,"indicaciones":""},{"medicamento":"Metformina 850 mg","dosis":"1 después de cenar.","duracion_dias":null,"indicaciones":""}]'::jsonb, 190),
  ('FASE 2', 'PASTILLAS 30 DIAS FASE 3', array[2]::int[], 'FASE 3: 30 días', '[{"medicamento":"Norex 50 mg","dosis":"1 en ayuno.","duracion_dias":null,"indicaciones":""},{"medicamento":"Lose 2 mg","dosis":"1 a las 4:00 pm.","duracion_dias":null,"indicaciones":""},{"medicamento":"Metformina 850 mg","dosis":"1 después de cenar.","duracion_dias":null,"indicaciones":""}]'::jsonb, 200),
  ('FASE 2', 'SAXENDA 3', array[2]::int[], 'FASE 3: 20 días', '[{"medicamento":"Saxenda (1) (10 días)","dosis":"1.8 mg diarios.","duracion_dias":10,"indicaciones":""}]'::jsonb, 210),
  ('FASE 2', 'WEGOVY COMBINADO FASE 3', array[2]::int[], 'FASE 3: 30 días', '[{"medicamento":"Diety Ap 20 mg","dosis":"1 en ayuno.","duracion_dias":null,"indicaciones":""},{"medicamento":"Acxion 30 mg","dosis":"1 a las 4:00 pm.","duracion_dias":null,"indicaciones":""},{"medicamento":"Metformina 850 mg","dosis":"1 después de cenar.","duracion_dias":null,"indicaciones":""},{"medicamento":"Wegovy 0.25 mg (1) (28 días)","dosis":"Aplicar 0.25 mg 1 vez a la semana, vía subcutánea por 4 semanas.\n- Alternar aplicación en brazos, piernas y abdomen.\n- Repetir la dosis el mismo día de la semana a la misma hora.\n- Después de algún alimento.","duracion_dias":28,"indicaciones":""}]'::jsonb, 220),
  ('FASE 2', 'WEGOVY FASE 3', array[2]::int[], 'FASE 3: 28 días', '[{"medicamento":"Wegovy 0.25 mg (1) (28 días)","dosis":"Aplicar 0.25 mg 1 vez a la semana, vía subcutánea por 4 semanas\n- Alternar la aplicacion en brazos, piernas y abdomen.\n- Repetir la dosis el mismo día de la semana a la misma hora.\n- Después de algún alimento.","duracion_dias":28,"indicaciones":""}]'::jsonb, 230),
  ('FASE 3 y 4', 'COMBINADO 15 DIAS.', array[3,4]::int[], 'FASE 5: 15 días', '[{"medicamento":"Norex 50 mg","dosis":"1 en ayuno.\n1 a las 4:00 pm.","duracion_dias":null,"indicaciones":""},{"medicamento":"Metformina 850 mg","dosis":"1 cada 12 horas, después del desayuno y la cena.\nEn caso de no tolerar, continuar con 1 después de cenar.","duracion_dias":null,"indicaciones":""},{"medicamento":"Saxenda (1) (10 días)","dosis":"1.8 mg diarios.","duracion_dias":10,"indicaciones":""}]'::jsonb, 240),
  ('FASE 3 y 4', 'COMBINADO FASE 5', array[3,4]::int[], 'FASE 5: 30 días', '[{"medicamento":"Diety Ap 20 mg","dosis":"1 en ayuno.","duracion_dias":null,"indicaciones":""},{"medicamento":"Acxion 30 mg","dosis":"1 a las 4:00 pm.","duracion_dias":null,"indicaciones":""},{"medicamento":"Metformina 850 mg","dosis":"1 cada 12 horas, después del desayuno y la cena.\nEn caso de no tolerar, continuar con 1 después de cenar.","duracion_dias":null,"indicaciones":""},{"medicamento":"Saxenda (1) (10 días)","dosis":"1.8 mg diarios.","duracion_dias":10,"indicaciones":""}]'::jsonb, 250),
  ('FASE 3 y 4', 'COMBINADO RYBELSUS', array[3,4]::int[], 'FASE 5: 30 días', '[{"medicamento":"Diety Ap 20 mg","dosis":"1 en ayuno.","duracion_dias":null,"indicaciones":""},{"medicamento":"Acxion 30 mg","dosis":"1 a las 4:00 pm.","duracion_dias":null,"indicaciones":""},{"medicamento":"Metformina 850 mg","dosis":"1 cada 12 horas, después del desayuno y la cena.\nEn caso de no tolerar, continuar con 1 después de cenar.","duracion_dias":null,"indicaciones":""},{"medicamento":"Rybelsus 7 mg (1) (30 días)","dosis":"1 diaria en ayuno, 30 minutos antes antes de desayunar\npor 30 días.","duracion_dias":30,"indicaciones":""}]'::jsonb, 260),
  ('FASE 3 y 4', 'KWIKPEN COMBINADO FASE 5', array[3,4]::int[], 'FASE 5: 30 días', '[{"medicamento":"Diety Ap 20 mg","dosis":"1 en ayuno.","duracion_dias":null,"indicaciones":""},{"medicamento":"Acxion 30 mg","dosis":"1 a las 4:00 pm.","duracion_dias":null,"indicaciones":""},{"medicamento":"Metformina 850 mg","dosis":"1 cada 12 horas, después del desayuno y la cena.\nEn caso de no tolerar, continuar con 1 después de cenar.","duracion_dias":null,"indicaciones":""},{"medicamento":"KwikPen 2.5 mg (1) (28 días)","dosis":"Aplicar 2.5 mg 1 vez a la semana, vía subcutánea por 4 semanas.\n- Alternar la aplicación en brazos, piernas y abdomen.\n- Repetir la dosis el mismo día de la semana a la misma hora.\n- Después de algún alimento.","duracion_dias":28,"indicaciones":""}]'::jsonb, 270),
  ('FASE 3 y 4', 'KWIKPEN FASE 5', array[3,4]::int[], 'FASE 5: 30 días', '[{"medicamento":"KwikPen 2.5 mg (1) (28 días)","dosis":"Aplicar 2.5 mg 1 vez a la semana, vía subcutánea por 4 semanas.\n- Alternar la aplicación en brazos, piernas y abdomen.\n- Repetir la dosis el mismo día de la semana a la misma hora.\n- Después de algún alimento.","duracion_dias":28,"indicaciones":""}]'::jsonb, 280),
  ('FASE 3 y 4', 'MOUNJARO COMBINADO FASE 5', array[3,4]::int[], 'FASE 5: 30 días', '[{"medicamento":"Diety Ap 20 mg","dosis":"1 en ayuno.","duracion_dias":null,"indicaciones":""},{"medicamento":"Lose 2 mg","dosis":"1 a las 4:00 pm.","duracion_dias":null,"indicaciones":""},{"medicamento":"Metformina 850 mg","dosis":"1 cada 12 horas, después del desayuno y la cena.\nEn caso de no tolerar, continuar con 1 después de cenar.","duracion_dias":null,"indicaciones":""},{"medicamento":"Mounjaro 2.5 mg. (1) (7 días)","dosis":"Aplicar 2.5 mg 1 vez a la semana, vía subcutánea,\npor 4 semanas, con jeringa de insulina.\n- Alternar la aplicación en brazo, piernas y abdomen.\n- Repetir la dosis el mismo día de la semana a la misma hora.\n- De preferencia después del desayuno o comida.","duracion_dias":7,"indicaciones":""}]'::jsonb, 290),
  ('FASE 3 y 4', 'PASTILLAS 15 DIAS FASE 5', array[3,4]::int[], 'FASE 5: 15 días', '[{"medicamento":"Norex 50 mg","dosis":"1 en ayuno.\n1 a las 4:00 pm.","duracion_dias":null,"indicaciones":""},{"medicamento":"Metformina 850 mg","dosis":"1 cada 12 horas, después del desayuno y la cena.\nEn caso de no tolerar, continuar con 1 después de cenar.","duracion_dias":null,"indicaciones":""}]'::jsonb, 300),
  ('FASE 3 y 4', 'PASTILLAS 30 DIAS FASE 5', array[3,4]::int[], 'FASE 5: 30 días', '[{"medicamento":"Norex 50 mg","dosis":"1 en ayuno.","duracion_dias":null,"indicaciones":""},{"medicamento":"Lose 2 mg","dosis":"1 a las 4:00 pm.","duracion_dias":null,"indicaciones":""},{"medicamento":"Metformina 850 mg","dosis":"1 cada 12 horas, después del desayuno y la cena.\nEn caso de no tolerar, continuar con 1 después de cenar.","duracion_dias":null,"indicaciones":""}]'::jsonb, 310),
  ('FASE 3 y 4', 'WEGOVY COMBINADO FASE 5', array[3,4]::int[], 'FASE 5: 30 días', '[{"medicamento":"Diety Ap 20 mg","dosis":"1 en ayuno.","duracion_dias":null,"indicaciones":""},{"medicamento":"Lose 2 mg","dosis":"1 a las 4:00 pm.","duracion_dias":null,"indicaciones":""},{"medicamento":"Metformina 850 mg","dosis":"1 cada 12 horas, después del desayuno y la cena.\nEn caso de no tolerar, continuar con 1 después de cenar.","duracion_dias":null,"indicaciones":""},{"medicamento":"Wegovy 0.25 mg (1) (28 días)","dosis":"Aplicar 0.25 mg 1 vez a la semana, vía subcutánea por 4 semanas\n- Alternar la aplicación en brazos, piernas y abdomen.\n- Repetir la dosis el mismo día de la semana a la misma hora.\n- De preferencia después del desayuno o comida.","duracion_dias":28,"indicaciones":""}]'::jsonb, 320),
  ('FASE 3 y 4', 'WEGOVY FASE 5', array[3,4]::int[], 'FASE 5: 28 días', '[{"medicamento":"Wegovy 0.25 mg (1) (28 días)","dosis":"Aplicar 0.25 mg 1 vez a la semana, vía subcutánea por 4 semanas\n- Alternar la aplicación en brazos, piernas y abdomen.\n- Repetir la dosis el mismo día de la semana a la misma hora.\n- De preferencia después del desayuno o comida.","duracion_dias":28,"indicaciones":""}]'::jsonb, 330),
  ('FASE 5', 'combinado 15 días-FEDRA', array[5]::int[], 'FASE 1: 15 días', '[{"medicamento":"Norex 50 mg","dosis":"1 en ayuno.\n1 a las 4:00 pm.","duracion_dias":null,"indicaciones":""},{"medicamento":"Metformina 850 mg","dosis":"1 después de cenar.","duracion_dias":null,"indicaciones":""},{"medicamento":"Victoza (1) (13 días)","dosis":"1) 0.6 mg x 3 días.\n2) 1.2 mg x 3 días.\n3) 1.8 mg lo restante.","duracion_dias":13,"indicaciones":""}]'::jsonb, 340),
  ('FASE 5', 'COMBINADO 21 DÍAS-FEDRA', array[5]::int[], 'FASE 1: 21 días', '[{"medicamento":"Diety Ap 20 mg","dosis":"1 en ayuno.\n1/2 a las 4:00 pm.","duracion_dias":null,"indicaciones":""},{"medicamento":"Metformina 850 mg","dosis":"1 después de cenar.","duracion_dias":null,"indicaciones":""},{"medicamento":"Victoza (1) (13 días)","dosis":"1) 0.6 mg x 3 días.\n2) 1.2 mg x 3 días.\n3) 1.8 mg lo restante.","duracion_dias":13,"indicaciones":""}]'::jsonb, 350),
  ('FASE 5', 'combinado 30 días 2 pastillas-FEDRA', array[5]::int[], 'FASE 1: 30 días', '[{"medicamento":"Norex 50 mg","dosis":"1 en ayuno.","duracion_dias":null,"indicaciones":""},{"medicamento":"Diety Ap 20 mg","dosis":"1 a las 4:00 pm.","duracion_dias":null,"indicaciones":""},{"medicamento":"Metformina 850 mg","dosis":"1 después de cenar.","duracion_dias":null,"indicaciones":""},{"medicamento":"Victoza (1) (13 días)","dosis":"1) 0.6 mg x 3 días.\n2) 1.2 mg x 3 días.\n3) 1.8 mg lo restante.","duracion_dias":13,"indicaciones":""}]'::jsonb, 360),
  ('FASE 5', 'Combinado Retomar 30 días 1 pastilla-FEDRA', array[5]::int[], 'FASE 1: 30 días', '[{"medicamento":"Diety Ap 20 mg","dosis":"1/2 en ayuno.\n1/2 a las 4:00 pm.","duracion_dias":null,"indicaciones":""},{"medicamento":"Metformina 850 mg","dosis":"1 después de cenar.","duracion_dias":null,"indicaciones":""},{"medicamento":"Victoza (1) (13 días)","dosis":"1) 0.6 mg x 3 días.\n2) 1.2 mg x 3 días.\n3) 1.8 mg lo restante.","duracion_dias":13,"indicaciones":""}]'::jsonb, 370),
  ('FASE 5', 'MOUNJARO COMBINADO RETOMAR', array[5]::int[], 'FASE 1: 21 días', '[{"medicamento":"Diety Ap 20 mg","dosis":"1 en ayuno.\n1/2 a las 4:00 pm.","duracion_dias":null,"indicaciones":""},{"medicamento":"Metformina 850 mg","dosis":"1 después de cenar.","duracion_dias":null,"indicaciones":""},{"medicamento":"Mounjaro 2.5 mg. (1) (7 días)","dosis":"Aplicar 2.5 mg 1 vez a la semana, vía subcutánea,\npor 4 semanas, con jeringa de insulina.\n- Alternar la aplicación en brazo, piernas y abdomen.\n- Repetir la dosis el mismo día de la semana a la misma hora.\n- De preferencia después del desayuno o comida.","duracion_dias":7,"indicaciones":""}]'::jsonb, 380),
  ('FASE 5', 'pastilla 21 días', array[5]::int[], 'FASE 1: 21 días', '[{"medicamento":"Norex 50 mg","dosis":"1 en ayuno.\n1/2 a las 4:00 pm.","duracion_dias":null,"indicaciones":""},{"medicamento":"Metformina 850 mg","dosis":"1 después de cenar.","duracion_dias":null,"indicaciones":""}]'::jsonb, 390),
  ('FASE 5', 'Pastillas 30 días 2 termogenicos', array[5]::int[], 'FASE 1: 30 días', '[{"medicamento":"Lose 20 mg","dosis":"1 en ayuno.","duracion_dias":null,"indicaciones":""},{"medicamento":"Norex 50 mg","dosis":"1 a las 4:00 pm.","duracion_dias":null,"indicaciones":""},{"medicamento":"Metformina 850 mg","dosis":"1 después de cenar.","duracion_dias":null,"indicaciones":""}]'::jsonb, 400),
  ('FASE 5', 'Retomar 30 días 1 pastilla', array[5]::int[], 'FASE 1: 30 días', '[{"medicamento":"Diety Ap 20 mg","dosis":"1/2 en ayuno.\n1/2 a las 4:00 pm.","duracion_dias":null,"indicaciones":""},{"medicamento":"Metformina 850 mg","dosis":"1 después de cenar.","duracion_dias":null,"indicaciones":""}]'::jsonb, 410),
  ('FASE 5', 'RETOMAR RYBELSUS Pastillas 30 días', array[5]::int[], 'FASE 1: 30 días', '[{"medicamento":"Lose 20 mg","dosis":"1 en ayuno.","duracion_dias":null,"indicaciones":""},{"medicamento":"Norex 50 mg","dosis":"1 a las 4:00 pm.","duracion_dias":null,"indicaciones":""},{"medicamento":"Metformina 850 mg","dosis":"1 después de cenar.","duracion_dias":null,"indicaciones":""},{"medicamento":"Rybelsus 7 mg (1) (30 días)","dosis":"1 diaria en ayuno, 30 minutos antes de desayunar\npor 30 días.","duracion_dias":30,"indicaciones":""}]'::jsonb, 420),
  ('FASE 5', 'Victoza 23 días', array[5]::int[], 'FASE 1: 23 días', '[{"medicamento":"Victoza (1) (13 días)","dosis":"1) 0.6 mg x 3 días.\n2) 1.2 mg x 3 días.\n3) 1.8 mg lo restante.","duracion_dias":13,"indicaciones":""}]'::jsonb, 430),
  ('FASE 5', 'WEGOVY COMBINADO RETOMAR 21 DIAS', array[5]::int[], 'FASE 1: 21 días', '[{"medicamento":"Lose 2 mg","dosis":"1 en ayuno.\n1/2 a las 4:00 pm.","duracion_dias":null,"indicaciones":""},{"medicamento":"Metformina 850 mg","dosis":"1 después de cenar.","duracion_dias":null,"indicaciones":""},{"medicamento":"Wegovy 0.25 mg (1) (28 días)","dosis":"Aplicar 0.25 mg 1 vez a la semana, vía subcutánea por 4 semanas\n- Alternar la aplicación en brazos, piernas y abdomen.\n- Repetir la dosis el mismo día de la semana a la misma hora.\n- De preferencia después del desayuno o comida.","duracion_dias":28,"indicaciones":""}]'::jsonb, 440),
  ('FASE 5', 'WEGOVY COMBINADO RETOMAR 30 DIAS', array[5]::int[], 'FASE 1: 30 días', '[{"medicamento":"Lose 2 mg","dosis":"1 en ayuno.","duracion_dias":null,"indicaciones":""},{"medicamento":"Norex 50 mg","dosis":"1 a las 4:00 pm.","duracion_dias":null,"indicaciones":""},{"medicamento":"Metformina 850 mg","dosis":"1 después de cenar.","duracion_dias":null,"indicaciones":""},{"medicamento":"Wegovy 0.25 mg (1) (28 días)","dosis":"Aplicar 0.25 mg 1 vez a la semana, vía subcutánea por 4 semanas\n- Alternar la aplicación en brazos, piernas y abdomen.\n- Repetir la dosis el mismo día de la semana a la misma hora.\n- De preferencia después del desayuno o comida.","duracion_dias":28,"indicaciones":""}]'::jsonb, 450),
  ('FASE 5', 'Wikpen COMBINADO RETOMAR 30 DIAS', array[5]::int[], 'FASE 1: 30 días', '[{"medicamento":"Lose 2 mg","dosis":"1 en ayuno.","duracion_dias":null,"indicaciones":""},{"medicamento":"Norex 50 mg","dosis":"1 a las 4:00 pm.","duracion_dias":null,"indicaciones":""},{"medicamento":"Metformina 850 mg","dosis":"1 después de cenar.","duracion_dias":null,"indicaciones":""},{"medicamento":"KwikPen 2.5mg (1) (28 días)","dosis":"Aplicar 2.5 mg 1 vez a la semana, vía subcutánea por 4 semanas\n- Alternar la aplicación en brazos, piernas y abdomen.\n- Repetir la dosis el mismo día de la semana a la misma hora.\n- De preferencia después del desayuno o comida.","duracion_dias":28,"indicaciones":""}]'::jsonb, 460),
  ('Mantenimiento', 'Mantenimiento 1 pastilla', array[]::int[], 'Mantenimiento', '[{"medicamento":"Acxion 30 mg","dosis":"1 en ayuno cada 48 hrs. hasta terminar.","duracion_dias":null,"indicaciones":""},{"medicamento":"Metformina 850 mg","dosis":"1 después de cenar.","duracion_dias":null,"indicaciones":""}]'::jsonb, 470),
  ('RETOMAR', 'DESTETE COMBINADO', array[]::int[], 'DESTETE: 35 días', '[{"medicamento":"Diety Ap 20 mg","dosis":"1) 1 en ayuno y 1 a las 4 pm x 5 días.\n2) 1 en ayuno c/24 hrs x 10 días.\n3) 1 en ayuno c/48 hrs x 20 días.","duracion_dias":null,"indicaciones":""},{"medicamento":"Metformina 850 mg","dosis":"1 después de cenar.","duracion_dias":null,"indicaciones":""},{"medicamento":"Saxenda (1) (15 días)","dosis":"1) 1.8 mg x 5 días.\n2) 1.2 mg x 5 días.\n3) 0.6 mg x 5 días.","duracion_dias":15,"indicaciones":""}]'::jsonb, 480),
  ('RETOMAR', 'DESTETE COMBINADO KWIKPEN', array[]::int[], 'DESTETE: 35 días', '[{"medicamento":"Diety Ap 20 mg","dosis":"1) 1 en ayuno y 1 a las 4 pm x 5 días.\n2) 1 en ayuno c/24 hrs x 10 días.\n3) 1 en ayuno c/48 hrs x 20 días.","duracion_dias":null,"indicaciones":""},{"medicamento":"Metformina 850 mg","dosis":"1 después de cenar.","duracion_dias":null,"indicaciones":""},{"medicamento":"KwikPen 2.5 mg. (1) (7 días)","dosis":"Aplicar 2.5 mg 1 vez a la semana, vía subcutánea,\npor 4 semanas, con jeringa de insulina.\n- Alternar la aplicación en brazo, piernas y abdomen.\n- Repetir la dosis el mismo día de la semana a la misma hora.\n- De preferencia después del desayuno o comida.","duracion_dias":7,"indicaciones":""}]'::jsonb, 490),
  ('RETOMAR', 'DESTETE COMBINADO WEGOBY', array[]::int[], 'DESTETE: 35 días', '[{"medicamento":"Diety Ap 20 mg","dosis":"1) 1 en ayuno y 1 a las 4 pm x 5 días.\n2) 1 en ayuno c/24 hrs x 10 días.\n3) 1 en ayuno c/48 hrs x 20 días.","duracion_dias":null,"indicaciones":""},{"medicamento":"Metformina 850 mg","dosis":"1 después de cenar.","duracion_dias":null,"indicaciones":""},{"medicamento":"Wegovy 0.5 mg. (1) (28 días)","dosis":"","duracion_dias":28,"indicaciones":""},{"medicamento":"Wegovy 0.25 mg (1) (28 días)","dosis":"Aplicar 0.25 mg 1 vez a la semana, vía subcutánea,\npor 4 semanas.\n- Alternar la aplicación en brazo, piernas y abdomen.\n- Repetir la dosis el mismo día de la semana a la misma hora.\n- De preferencia después del desayuno o comida.","duracion_dias":28,"indicaciones":""}]'::jsonb, 500),
  ('RETOMAR', 'DESTETE MOUNJARO', array[]::int[], 'DESTETE: 14 días', '[{"medicamento":"Mounjaro 5 mg. (2) (14 días)","dosis":"Aplicar 5 mg 1 vez a la semana, vía subcutánea,\npor 2 semanas.\n- Alternar la aplicación en brazo, piernas y abdomen.\n- Repetir la dosis el mismo día de la semana a la misma hora.\n- De preferencia después del desayuno o comida.","duracion_dias":14,"indicaciones":""}]'::jsonb, 510),
  ('RETOMAR', 'DESTETE PASTILLA', array[]::int[], 'DESTETE: 35 días', '[{"medicamento":"Acxion 30 mg","dosis":"1) 1 en ayuno y 1 a las 4 pm x 5 días.\n2) 1 en ayuno c/24 hrs x 10 días.\n3) 1 en ayuno c/48 hrs x 20 días.","duracion_dias":null,"indicaciones":""},{"medicamento":"Metformina 850 mg","dosis":"1 después de cenar.","duracion_dias":null,"indicaciones":""}]'::jsonb, 520),
  ('RETOMAR', 'DESTETE SAXENDA', array[]::int[], 'DESTETE: 15 días', '[{"medicamento":"Saxenda (1) (15 días)","dosis":"1.8 mg x 5 días.\n1.2 mg x 5 días.\n0.6 mg x 5 días.","duracion_dias":15,"indicaciones":""}]'::jsonb, 530)
on conflict (categoria, nombre) do nothing;
